export interface LandingPageConfig {
  id: string;
  path: string;
  title: string;
  navLabel: string;
  icon: string;
  headline: string;
  subtitle: string;
  philosophy: string;
  features: string[];
  status: 'live' | 'building' | 'planned';
  dashtwoPrompt: string;
}

export const LANDING_PAGES: LandingPageConfig[] = [
  {
    id: 'dashtwo',
    path: '/dashtwo',
    title: 'DashTwo — AI Aviation Wingman',
    navLabel: 'DashTwo',
    icon: 'chat',
    headline: 'AI Aviation Wingman',
    subtitle: 'Ask anything about regulations, checkride prep, training, or aviation careers. Every answer backed by 515K+ FAA documents with source citations.',
    philosophy: '',
    features: [],
    status: 'live',
    dashtwoPrompt: '',
  },
  {
    id: 'dashboard',
    path: '/dashtwo/dashboard',
    title: 'Pilot Dashboard — Tally Aero',
    navLabel: 'Dashboard',
    icon: 'home',
    headline: 'Your Flight Data Tells a Story',
    subtitle: 'The dashboard reads it so you don\'t have to do the math.',
    philosophy: 'Every pilot accumulates data — hours, ratings, currency dates, trends. Most of it sits in logbooks and spreadsheets, disconnected from meaning. The dashboard brings it together into a single view: where you are, where you\'re going, and what needs attention today. Not vanity metrics. Operational awareness.',
    features: [
      'Career overview with certificate progression timeline',
      'Currency status widgets with automatic expiration tracking',
      'Recent activity feed — flights, training, checkride prep',
      'Skill status at a glance — five-component breakdown',
      'Upcoming flights and preparation reminders',
      'DashTwo integration — ask questions about your data',
    ],
    status: 'building',
    dashtwoPrompt: 'What should I focus on to make progress toward my next certificate?',
  },
  {
    id: 'logbook',
    path: '/dashtwo/logbook',
    title: 'Digital Logbook — Tally Aero',
    navLabel: 'Logbook',
    icon: 'book',
    headline: 'A Logbook That Understands What You Logged',
    subtitle: 'Not just fields in a spreadsheet — regulatory meaning.',
    philosophy: 'Most digital logbooks are glorified databases. They store numbers but don\'t understand what those numbers mean under 14 CFR. Tally Aero\'s logbook knows the difference between PIC time under Part 61.51(e) and SIC time under Part 135. It understands that night currency and instrument currency have different lookback windows. It catches the mistakes before the DPE does.',
    features: [
      'Full flight entry with regulatory field validation',
      'Import from ForeFlight, paper logbooks, or Excel',
      'Automatic currency calculation from flight entries',
      'Column layout editor — customize your view',
      'Military flight time conversion',
      'Context logbooks for historical data preservation',
      'PIC/SIC/dual/solo time rules enforced correctly',
    ],
    status: 'building',
    dashtwoPrompt: 'What are the rules for logging PIC time vs SIC time?',
  },
  {
    id: 'currency',
    path: '/dashtwo/currency',
    title: 'Currency Tracking — Tally Aero',
    navLabel: 'Currency',
    icon: 'shield',
    headline: 'Currency Is Binary',
    subtitle: 'You\'re either current or you\'re not. Let the logbook do the math.',
    philosophy: 'Currency calculations are deceptively complex. Day/night passenger currency, instrument currency, flight review — each has different lookback periods, different qualifying events, and different regulatory references. Pilots manually tracking this make mistakes. The consequence of getting it wrong isn\'t a failed checkride — it\'s operating illegally. Automate the calculation. Eliminate the risk.',
    features: [
      'Day and night passenger currency (61.57(a))',
      'Instrument currency with approach/hold/tracking (61.57(c))',
      'Flight review tracking (61.56)',
      'Medical certificate expiration with age-based rules',
      'Upcoming lapse warnings — never be surprised',
      'Category/class-specific currency tracking',
    ],
    status: 'building',
    dashtwoPrompt: 'Explain the instrument currency requirements under 14 CFR 61.57(c).',
  },
  {
    id: 'reports',
    path: '/dashtwo/reports',
    title: 'Flight Reports — Tally Aero',
    navLabel: 'Reports',
    icon: 'chart',
    headline: 'Raw Hours Don\'t Tell You If You\'re Improving',
    subtitle: 'Trends do.',
    philosophy: 'A pilot with 500 hours and plateauing skills is not better off than a pilot with 200 hours on an improvement trajectory. Time in the logbook is necessary but not sufficient. Reports transform your flight data into trends — are you getting better at crosswind landings? Is your instrument approach precision improving? Are you flying enough to maintain proficiency, or is there decay?',
    features: [
      'Flight time analysis by category, class, and condition',
      'Training progress visualization over time',
      'Trend analysis — improvement, plateau, or decay detection',
      'Custom report generation for insurance or employment',
      'Logbook totals with regulatory breakdowns',
    ],
    status: 'building',
    dashtwoPrompt: 'How many hours do I need for a commercial pilot certificate?',
  },
  {
    id: 'training',
    path: '/dashtwo/training',
    title: 'Training Tools — Tally Aero',
    navLabel: 'Training',
    icon: 'academic',
    headline: 'The Airplane Is a Performance Environment',
    subtitle: 'Deliberate practice happens on the ground. These tools isolate each component of skill.',
    philosophy: 'You wouldn\'t practice free throws for the first time during a game. Yet most pilot training happens exclusively in the airplane — the most expensive, time-pressured, high-stakes environment possible. Ground-based deliberate practice isolates individual skills: radio communication, mental math, spatial orientation, emergency procedures. Build the components separately, then integrate them in flight.',
    features: [
      'Comm Drill — ATC radio practice with speech recognition scoring',
      'Comm Sheet Generator — 330+ radio calls for any phase of flight',
      'Drill Machine — 44 mental math drills (headings, fuel, distance/time)',
      'Holding Pattern Trainer — 500+ real navaids with entry procedures',
      'Stall/Spin Awareness — 110+ aircraft aerodynamic profiles',
      'Landing Lab — visual approach geometry for 15 aircraft types',
      'Reciprocal Headings — 5 difficulty levels for instant heading math',
      'Rules of Thumb — 130+ aviation rules with 39 practice drills',
      'EM Diagram — energy management for 100+ aircraft',
      'Maneuver Overlay — satellite imagery for practice area planning',
      'Talk On — voice spatial communication practice',
      'SA Exercises — ATC tabletop situational awareness',
      'EP Recordings — audio emergency procedure drills',
    ],
    status: 'building',
    dashtwoPrompt: 'I\'m struggling with crosswind landings. What should I practice?',
  },
  {
    id: 'pilotiq',
    path: '/dashtwo/pilotiq',
    title: 'PilotIQ Skill Vectors — Tally Aero',
    navLabel: 'PilotIQ',
    icon: 'brain',
    headline: '"Get Better at Landings" Is Not a Plan',
    subtitle: 'Which component is breaking down? Knowledge? Scan? Physicality? Diagnosis before prescription.',
    philosophy: 'Every aviation maneuver is built from five components of skill: Knowledge (K), Aeronautical Decision-Making (ADM), Scan (S), Physicality (P), and Communication (C). When a landing goes wrong, it\'s not because "landings are hard." It\'s because one specific component broke down — maybe the scan didn\'t transition from instrument to visual at the right time, or the physical inputs didn\'t account for the crosswind gradient. PilotIQ diagnoses which component needs work and prescribes targeted practice.',
    features: [
      'Five-component skill tracking (K/ADM/S/P/C) per maneuver',
      '0-3 scoring with detailed rubrics',
      'Skill decay tracking — see what\'s getting rusty',
      'Component-weighted practice sequences',
      'Master maneuver library with standards',
      'Trend analysis showing improvement or plateau per component',
    ],
    status: 'building',
    dashtwoPrompt: 'Explain the five components of skill framework for aviation.',
  },
  {
    id: 'career',
    path: '/dashtwo/career',
    title: 'Career Progression — Tally Aero',
    navLabel: 'Career',
    icon: 'briefcase',
    headline: 'Every Pilot Has a Career Arc',
    subtitle: 'See where you are, where you\'re going, and what\'s between you and the next milestone.',
    philosophy: 'The path from student pilot to ATP is well-defined by regulation but poorly understood in practice. How many hours until you qualify for your instrument rating? What endorsements do you still need? When should you start your commercial training? Career progression tracking maps your actual logbook data against regulatory requirements, showing exactly where you stand and what comes next.',
    features: [
      'Certificate and rating progression timeline',
      'Requirements mapping — logbook data vs. regulatory minimums',
      'Endorsement tracking and management',
      'Type rating progression for multi-engine and turbine pilots',
      'Flight time milestone alerts',
      'Career path planning with DashTwo guidance',
    ],
    status: 'building',
    dashtwoPrompt: 'What are the requirements for an instrument rating?',
  },
  {
    id: 'checkride',
    path: '/dashtwo/checkride',
    title: 'Checkride Prep — Tally Aero',
    navLabel: 'Checkride',
    icon: 'clipboard',
    headline: 'The DPE Can\'t Find the Edges of Your Knowledge',
    subtitle: 'Checkride prep isn\'t memorizing answers — it\'s building understanding deep enough.',
    philosophy: 'The ACS doesn\'t test memorization — it tests understanding. A DPE who asks "what are the requirements for VFR flight" isn\'t looking for a recited list. They\'re looking for a pilot who understands WHY those requirements exist and can apply them to novel scenarios. DashTwo\'s checkride mode simulates a real DPE oral: follow-up questions, scenario-based probing, and honest assessment of your readiness.',
    features: [
      'DPE oral exam simulation with realistic follow-ups',
      'ACS standards mapped to your actual skill data',
      'Readiness assessment based on proficiency scores',
      'Study plans generated from your weak areas',
      'Practice and exam modes (exam mode: no feedback until the end)',
      'All certificates: Private, Instrument, Commercial, CFI, ATP',
    ],
    status: 'building',
    dashtwoPrompt: 'Run me through a private pilot oral exam on weather.',
  },
  {
    id: 'dpe',
    path: '/dashtwo/dpe',
    title: 'DPE Portal — Tally Aero',
    navLabel: 'DPE Portal',
    icon: 'badge',
    headline: 'The Other Side of the Checkride',
    subtitle: 'Tools built for examiners, not just examinees.',
    philosophy: 'Designated Pilot Examiners manage a complex business — applicant scheduling, evaluation documentation, IACRA processing, and continuous compliance with FAA standards. The DPE Portal brings structure to that workflow with tools designed by people who understand both sides of the checkride table.',
    features: [
      'Applicant management and scheduling',
      'Evaluation forms aligned with current ACS/PTS',
      'Automated reporting for FSDO compliance',
      'Checkride history and outcome tracking',
      'Integration with IACRA workflows',
    ],
    status: 'planned',
    dashtwoPrompt: 'What are the DPE requirements and evaluation standards?',
  },
  {
    id: 'aircraft',
    path: '/dashtwo/aircraft',
    title: 'Aircraft Profiles — Tally Aero',
    navLabel: 'Aircraft',
    icon: 'plane',
    headline: 'Your Airplane Has a Story Too',
    subtitle: 'Maintenance cycles, performance data, documents. Every tool should know what you fly.',
    philosophy: 'An aircraft isn\'t just a tail number in a logbook entry. It has V-speeds, limitations, systems, maintenance history, and documents that affect how you train, plan, and fly. When DashTwo knows your aircraft, every answer gets specific — not "the typical Cessna 172" but "your 172S with the G1000."',
    features: [
      'Aircraft profiles by tail number with auto-population from FAA registry',
      'V-speeds, limitations, and systems reference',
      'Document library — POH, supplements, checklists',
      'Maintenance tracking integration',
      'Connected to logbook entries and training tools',
      'EP recordings configured for your aircraft\'s systems',
    ],
    status: 'building',
    dashtwoPrompt: 'What are the V-speeds for a Cessna 172S?',
  },
  {
    id: 'docs',
    path: '/dashtwo/docs',
    title: 'Document Library — Tally Aero',
    navLabel: 'Docs',
    icon: 'folder',
    headline: 'Your Documents Should Work for You',
    subtitle: 'Not sit in a drawer. When DashTwo knows your POH, every answer gets aircraft-specific.',
    philosophy: 'Pilots accumulate documents — POH, supplements, ADs, service bulletins, insurance papers, training records. Most of it lives in scattered PDFs, binders, and email attachments. The document library centralizes everything and makes it searchable by DashTwo. Upload your POH and suddenly DashTwo can answer questions about YOUR airplane\'s specific procedures, not generic handbook answers.',
    features: [
      'Upload and organize aviation documents (PDF, images)',
      'OCR processing for scanned paper documents',
      'Integrated into DashTwo\'s knowledge base',
      'Full-text search across all your documents',
      'Shared aircraft document library',
      'Personal supplements and custom checklists',
    ],
    status: 'building',
    dashtwoPrompt: 'How should I organize my aviation documents?',
  },
  {
    id: 'safety',
    path: '/dashtwo/safety',
    title: 'Safety & Risk — Tally Aero',
    navLabel: 'Safety',
    icon: 'warning',
    headline: 'Safety Isn\'t a Checklist',
    subtitle: 'It\'s a culture. Track hazards, analyze trends, make the invisible visible.',
    philosophy: 'The accidents that kill GA pilots aren\'t caused by mechanical failure — they\'re caused by decision-making failures that were invisible to the pilot at the time. Risk assessment tools don\'t prevent accidents by saying "don\'t fly." They prevent accidents by making risk factors visible so the pilot can make an informed decision. Trend analysis reveals patterns that individual flights hide.',
    features: [
      'Pre-flight risk assessment with scoring',
      'Hazard identification and tracking',
      'Personal safety trend analysis',
      'Incident reporting and review',
      'Integration with weather and NOTAM data',
      'DashTwo risk discussion for flight planning',
    ],
    status: 'planned',
    dashtwoPrompt: 'What are the most common risk factors in general aviation accidents?',
  },
  {
    id: 'achievements',
    path: '/dashtwo/achievements',
    title: 'Achievements — Tally Aero',
    navLabel: 'Achievements',
    icon: 'trophy',
    headline: 'Rewards the Behaviors That Produce Improvement',
    subtitle: 'Consistency, honesty, specificity, follow-through. Not participation trophies.',
    philosophy: 'Gamification in aviation training is usually superficial — badges for logging flights, streaks for showing up. Tally Aero\'s achievement system rewards the behaviors that actually correlate with skill development: consistent debriefing, finding your own imperfections, completing prescribed practice, tracking improvement trends, and accurate self-assessment calibration.',
    features: [
      'Debrief streaks — build the habit of structured reflection',
      'Honest Broker — reward for identifying imperfections in your own flying',
      'Closer — complete prescribed training tasks',
      'Trend Setter — demonstrate measurable improvement over flights',
      'Self-Aware — calibration accuracy between self-assessment and data',
      'Deep Diver — thorough analysis of complex scenarios',
    ],
    status: 'planned',
    dashtwoPrompt: 'How do I build consistent training habits as a pilot?',
  },
];
